import type { Metadata } from "next";
import "./globals.css";
import Header from "./_header/page";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Site de Vendas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Header />
          {children}
          <Toaster position="top-left" />
        </AuthProvider>
      </body>
    </html>
  );
}
